name: Docker

on:
  push:
    branches:
    - main
  repository_dispatch:
    types: d2-build-image-trigger
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/pesca-dev/d2
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=long
    - name: Build and Push image
      uses: docker/build-push-action@v4
      with:
        context: d2
        platforms: linux/amd64,linux/arm64/v8
        network: host
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
